// GENERATED by scripts/load — do not edit. Proves src/server.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/server.ts", async () => {
  const mod = await import("../../src/server.js");
  expect(mod).toBeDefined();
});
