// GENERATED by scripts/load — do not edit. Proves src/adapters/github.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/adapters/github.ts", async () => {
  const mod = await import("../../src/adapters/github.js");
  expect(mod).toBeDefined();
});
